/*const initialPatients: Patient[] = [
  {
    id: 1,
    queueNo: 1,
    name: "Harsh Swami",
    email: "ken99@yahoo.com",
    phone: "+91 9832893023",
    age: 19,
    date: "Today",
    status: "waiting",
  },
  {
    id: 2,
    queueNo: 2,
    name: "Ankit Singh",
    email: "ankit@yahoo.com",
    phone: "+91 9876543210",
    age: 25,
    date: "Today",
    status: "serving",
  },
  {
    id: 3,
    queueNo: 3,
    name: "Riya Shah",
    email: "riya@gmail.com",
    phone: "+91 9988776655",
    age: 22,
    date: "Today",
    status: "completed",
  },
  {
    id: 4,
    queueNo: 4,
    name: "Aman Verma",
    email: "aman.verma@example.com",
    phone: "+91 9765432101",
    age: 30,
    date: "Today",
    status: "waiting",
  },
  {
    id: 5,
    queueNo: 5,
    name: "Pooja Gupta",
    email: "pooja.gupta@example.com",
    phone: "+91 9845678901",
    age: 28,
    date: "Today",
    status: "serving",
  },
  {
    id: 6,
    queueNo: 6,
    name: "Vikram Rao",
    email: "vikram.rao@example.com",
    phone: "+91 9008765432",
    age: 35,
    date: "Today",
    status: "waiting",
  },
  {
    id: 7,
    queueNo: 7,
    name: "Neha Patel",
    email: "neha.patel@example.com",
    phone: "+91 9234567890",
    age: 24,
    date: "Today",
    status: "completed",
  },
  {
    id: 8,
    queueNo: 8,
    name: "Rajesh Kumar",
    email: "rajesh.kumar@example.com",
    phone: "+91 9501234567",
    age: 40,
    date: "Today",
    status: "waiting",
  },
  {
    id: 9,
    queueNo: 9,
    name: "Anjali Mehta",
    email: "anjali.mehta@example.com",
    phone: "+91 9098765432",
    age: 26,
    date: "Today",
    status: "serving",
  },
  {
    id: 10,
    queueNo: 10,
    name: "Sunil Yadav",
    email: "sunil.yadav@example.com",
    phone: "+91 9376543210",
    age: 32,
    date: "Today",
    status: "completed",
  },
  {
    id: 11,
    queueNo: 11,
    name: "Shreya Agarwal",
    email: "shreya.agarwal@example.com",
    phone: "+91 9801234567",
    age: 27,
    date: "Today",
    status: "waiting",
  },
  {
    id: 12,
    queueNo: 12,
    name: "Deepak Joshi",
    email: "deepak.joshi@example.com",
    phone: "+91 9912345678",
    age: 31,
    date: "Today",
    status: "serving",
  },
  {
    id: 13,
    queueNo: 13,
    name: "Suman Singh",
    email: "suman.singh@example.com",
    phone: "+91 9887654321",
    age: 38,
    date: "Today",
    status: "waiting",
  },
  {
    id: 14,
    queueNo: 14,
    name: "Kriti Sharma",
    email: "kriti.sharma@example.com",
    phone: "+91 9776543210",
    age: 23,
    date: "Today",
    status: "completed",
  },
  {
    id: 15,
    queueNo: 15,
    name: "Manish Reddy",
    email: "manish.reddy@example.com",
    phone: "+91 9609876543",
    age: 29,
    date: "Today",
    status: "waiting",
  },
  {
    id: 16,
    queueNo: 16,
    name: "Priya Nair",
    email: "priya.nair@example.com",
    phone: "+91 9512345678",
    age: 33,
    date: "Today",
    status: "serving",
  },
  {
    id: 17,
    queueNo: 17,
    name: "Ravi Kapoor",
    email: "ravi.kapoor@example.com",
    phone: "+91 9245678901",
    age: 41,
    date: "Today",
    status: "completed",
  },
  {
    id: 18,
    queueNo: 18,
    name: "Sonal Desai",
    email: "sonal.desai@example.com",
    phone: "+91 9487654321",
    age: 26,
    date: "Today",
    status: "waiting",
  },
  {
    id: 9,
    queueNo: 9,
    name: "Anjali Mehta",
    email: "anjali.mehta@example.com",
    phone: "+91 9098765432",
    age: 26,
    date: "Today",
    status: "serving",
  },
  {
    id: 10,
    queueNo: 10,
    name: "Sunil Yadav",
    email: "sunil.yadav@example.com",
    phone: "+91 9376543210",
    age: 32,
    date: "Today",
    status: "completed",
  },
  {
    id: 11,
    queueNo: 11,
    name: "Shreya Agarwal",
    email: "shreya.agarwal@example.com",
    phone: "+91 9801234567",
    age: 27,
    date: "Today",
    status: "waiting",
  },
  {
    id: 12,
    queueNo: 12,
    name: "Deepak Joshi",
    email: "deepak.joshi@example.com",
    phone: "+91 9912345678",
    age: 31,
    date: "Today",
    status: "serving",
  },
  {
    id: 13,
    queueNo: 13,
    name: "Suman Singh",
    email: "suman.singh@example.com",
    phone: "+91 9887654321",
    age: 38,
    date: "Today",
    status: "waiting",
  },
  {
    id: 14,
    queueNo: 14,
    name: "Kriti Sharma",
    email: "kriti.sharma@example.com",
    phone: "+91 9776543210",
    age: 23,
    date: "Today",
    status: "completed",
  },
  {
    id: 15,
    queueNo: 15,
    name: "Manish Reddy",
    email: "manish.reddy@example.com",
    phone: "+91 9609876543",
    age: 29,
    date: "Today",
    status: "waiting",
  },
  {
    id: 16,
    queueNo: 16,
    name: "Priya Nair",
    email: "priya.nair@example.com",
    phone: "+91 9512345678",
    age: 33,
    date: "Today",
    status: "serving",
  },
  {
    id: 19,
    queueNo: 19,
    name: "Nikhil Agarwal",
    email: "nikhil.agarwal@example.com",
    phone: "+91 9612345678",
    age: 34,
    date: "Today",
    status: "serving",
  },
  {
    id: 20,
    queueNo: 20,
    name: "Aarti Joshi",
    email: "aarti.joshi@example.com",
    phone: "+91 9743234567",
    age: 29,
    date: "Today",
    status: "completed",
  },
  {
    id: 21,
    queueNo: 21,
    name: "Amit Soni",
    email: "amit.soni@example.com",
    phone: "+91 9384765432",
    age: 27,
    date: "Today",
    status: "waiting",
  },
  {
    id: 22,
    queueNo: 22,
    name: "Vandana Bhatia",
    email: "vandana.bhatia@example.com",
    phone: "+91 9224567890",
    age: 30,
    date: "Today",
    status: "serving",
  },
  {
    id: 23,
    queueNo: 23,
    name: "Karan Mehta",
    email: "karan.mehta@example.com",
    phone: "+91 9536789012",
    age: 24,
    date: "Today",
    status: "waiting",
  },
  {
    id: 24,
    queueNo: 24,
    name: "Geeta Verma",
    email: "geeta.verma@example.com",
    phone: "+91 9476543210",
    age: 39,
    date: "Today",
    status: "completed",
  },
  {
    id: 25,
    queueNo: 25,
    name: "Sandeep Kumar",
    email: "sandeep.kumar@example.com",
    phone: "+91 9087654321",
    age: 37,
    date: "Today",
    status: "waiting",
  },
];*/
