import type { Metadata } from "next";
import { ReduxProvider } from './redux/ReduxProvider'
import localFont from "next/font/local";
import "./globals.css";
import "./layout.css";


type Props = {
  pathname: string;
  children: React.ReactNode;
};

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  pathname,
  children,
}: Readonly<{
  pathname: string;
  children: React.ReactNode;
}>) {
  const getActiveMenuName = (path: string) => {
    switch (pathname) {
      case "/dashboard":
        return "Dashboard";
      case "/queue":
        return "My Queue";
      case "/appointment":
        return "Appointments";
      case "/settings":
        return "Settings";
      default:
        return "Dashboard"; // Default case if no match
    }
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-full overflow-hidden antialiased`}
      >
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
