import type { Metadata } from "next";
import { ReduxProvider } from './redux/ReduxProvider'
import localFont from "next/font/local";
import "./globals.css";
import "./layout.css";


type Props = {
  pathname: string;
  children: React.ReactNode;
};

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "CareQ",
  description: "Generated by create next app",
};

export default function RootLayout({
  pathname,
  children,
}: Readonly<{
  pathname: string;
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-full  antialiased`}
      >
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
