import type { Metadata } from "next";
import { cookies } from "next/headers";
import { GetServerSideProps } from "next";
import { usePathname } from "next/navigation";
import localFont from "next/font/local";
import DoctorHeader from "./DoctorHeader"; 
import "../globals.css";
import React, { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import "../layout.css";
import { ComboboxDemo } from "@/components/ui/clinic-select";
import { Button } from "@/components/ui/button";
import Sidebar from "./sidemenu";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Stringifier } from "postcss";
import path from "path";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import ClinicSetting from "./clinicSetting";

type Props = {
  pathname: string;
  children: React.ReactNode;
};

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function DoctorLayout({ children }: { children: React.ReactNode }){
  
  const getActiveMenuName = (path: string) => {
  };

  return (
    <section className="h-screen overflow-hidden">
      <div className="flex flex-row h-full w-full gap-1 bg-secondary]">
        {/* Code for the Left menu */}

        
          
        <Sidebar></Sidebar>
          


        <div className="flex flex-col bg-gray-50 h-full items-center justify-start rounded-xl w-[100%] border-b-gray-500 border-b-2">
          <div className=" bg-white w-[100%] rounded-tl-lg flex item-center justify-between px-4 h-16 py-1">
            <div className="font-semibold flex items-center text-secondary text-lg">
              Queue Management
            </div>
            <div className="flex gap-6 items-center">
              <div className=" flex gap-6">
                <ComboboxDemo />
                <ClinicSetting></ClinicSetting>

                
              </div>
              <DoctorHeader />
            </div>
          </div>
          <div className=" h-full w-full overflow-hidden">{children}</div>
        </div>
      </div>
    </section>
  );
}
