import type { Metadata } from "next";
import { GetServerSideProps } from "next";
import { usePathname } from "next/navigation";
import localFont from "next/font/local";
import "../globals.css";
import React, { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import "../layout.css";
import { ComboboxDemo } from "@/components/ui/clinic-select";
import { Button } from "@/components/ui/button";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Stringifier } from "postcss";
import path from "path";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

type Props = {
  pathname: string;
  children: React.ReactNode;
};

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DoctorLayout({
  pathname,
  children,
}: Readonly<{
  pathname: string;
  children: React.ReactNode;
}>) {
  const getActiveMenuName = (path: string) => {
    switch (pathname) {
      case "/dashboard":
        return "Dashboard";
      case "/queue":
        return "My Queue";
      case "/appointment":
        return "Appointments";
      case "/settings":
        return "Settings";
      default:
        return "Dashboard"; // Default case if no match
    }
  };

  return (
    <section>
      <div className="flex flex-row h-[100vh] gap-1 bg-secondary]">
        {/* Code for the Left menu */}

        <div className="left-menu">
          <div className="flex flex-col gap-8 w-full justify-start">
            <div className="mainlogo">
              <Image src="/circle-logo.svg" alt="icon" width={35} height={35} />
              <div className="carelogo">
                Care<span className="qlogo">Q</span>
              </div>
            </div>

            <div className="flex flex-col gap-2 w-full ">
              <Button
                variant={"ghost"}
                className="flex justify-start hover:bg-white/5 p-4 w-full"
              >
                <Link href="/doctor" passHref>
                  <div className="dashboardIcons">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="48"
                      height="48"
                      viewBox="0 0 25 25"
                      fill="none"
                    >
                      <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M12.5 2.08984C9.35397 2.08984 6.80359 4.64022 6.80359 7.78627C6.80359 10.3837 8.54197 12.575 10.9187 13.2604C9.04241 13.489 7.43306 14.1527 6.2207 15.3475C4.67769 16.8681 3.89648 19.132 3.89648 22.0862C3.89648 22.4984 4.23067 22.8326 4.64291 22.8326C5.05515 22.8326 5.38934 22.4984 5.38934 22.0862C5.38934 19.3833 6.10094 17.5615 7.26858 16.4107C8.43843 15.2578 10.1849 14.6613 12.4999 14.6613C14.815 14.6613 16.5615 15.2578 17.7314 16.4108C18.8991 17.5615 19.6107 19.3833 19.6107 22.0862C19.6107 22.4984 19.9448 22.8326 20.3571 22.8326C20.7693 22.8326 21.1035 22.4984 21.1035 22.0862C21.1036 19.132 20.3223 16.8681 18.7793 15.3475C17.5669 14.1527 15.9576 13.489 14.0813 13.2604C16.458 12.575 18.1964 10.3837 18.1964 7.78627C18.1964 4.64022 15.6461 2.08984 12.5 2.08984ZM8.29645 7.78627C8.29645 5.4647 10.1784 3.5827 12.5 3.5827C14.8216 3.5827 16.7036 5.4647 16.7036 7.78627C16.7036 10.1078 14.8216 11.9898 12.5 11.9898C10.1784 11.9898 8.29645 10.1078 8.29645 7.78627Z"
                        fill="white"
                      />
                    </svg>
                    <p className="text-white text-[15px]">Dashboard</p>
                  </div>
                </Link>
              </Button>

              <Button
                variant={"ghost"}
                className="flex justify-start hover:bg-white/5 p-4 w-full"
              >
                <Link href="/doctor/appointment" passHref>
                  <div className="dashboardIcons">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="48"
                      height="48"
                      viewBox="0 0 25 25"
                      fill="none"
                    >
                      <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M12.5 2.08984C9.35397 2.08984 6.80359 4.64022 6.80359 7.78627C6.80359 10.3837 8.54197 12.575 10.9187 13.2604C9.04241 13.489 7.43306 14.1527 6.2207 15.3475C4.67769 16.8681 3.89648 19.132 3.89648 22.0862C3.89648 22.4984 4.23067 22.8326 4.64291 22.8326C5.05515 22.8326 5.38934 22.4984 5.38934 22.0862C5.38934 19.3833 6.10094 17.5615 7.26858 16.4107C8.43843 15.2578 10.1849 14.6613 12.4999 14.6613C14.815 14.6613 16.5615 15.2578 17.7314 16.4108C18.8991 17.5615 19.6107 19.3833 19.6107 22.0862C19.6107 22.4984 19.9448 22.8326 20.3571 22.8326C20.7693 22.8326 21.1035 22.4984 21.1035 22.0862C21.1036 19.132 20.3223 16.8681 18.7793 15.3475C17.5669 14.1527 15.9576 13.489 14.0813 13.2604C16.458 12.575 18.1964 10.3837 18.1964 7.78627C18.1964 4.64022 15.6461 2.08984 12.5 2.08984ZM8.29645 7.78627C8.29645 5.4647 10.1784 3.5827 12.5 3.5827C14.8216 3.5827 16.7036 5.4647 16.7036 7.78627C16.7036 10.1078 14.8216 11.9898 12.5 11.9898C10.1784 11.9898 8.29645 10.1078 8.29645 7.78627Z"
                        fill="white"
                      />
                    </svg>
                    <p className="text-white text-[15px]">My Queue</p>
                  </div>
                </Link>
              </Button>

              <Button
                variant={"ghost"}
                className="flex justify-start hover:bg-white/5 p-4 w-full"
              >
                <Link href="/doctor" passHref>
                  <div className="dashboardIcons">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="48"
                      height="48"
                      viewBox="0 0 25 25"
                      fill="none"
                    >
                      <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M12.5 2.08984C9.35397 2.08984 6.80359 4.64022 6.80359 7.78627C6.80359 10.3837 8.54197 12.575 10.9187 13.2604C9.04241 13.489 7.43306 14.1527 6.2207 15.3475C4.67769 16.8681 3.89648 19.132 3.89648 22.0862C3.89648 22.4984 4.23067 22.8326 4.64291 22.8326C5.05515 22.8326 5.38934 22.4984 5.38934 22.0862C5.38934 19.3833 6.10094 17.5615 7.26858 16.4107C8.43843 15.2578 10.1849 14.6613 12.4999 14.6613C14.815 14.6613 16.5615 15.2578 17.7314 16.4108C18.8991 17.5615 19.6107 19.3833 19.6107 22.0862C19.6107 22.4984 19.9448 22.8326 20.3571 22.8326C20.7693 22.8326 21.1035 22.4984 21.1035 22.0862C21.1036 19.132 20.3223 16.8681 18.7793 15.3475C17.5669 14.1527 15.9576 13.489 14.0813 13.2604C16.458 12.575 18.1964 10.3837 18.1964 7.78627C18.1964 4.64022 15.6461 2.08984 12.5 2.08984ZM8.29645 7.78627C8.29645 5.4647 10.1784 3.5827 12.5 3.5827C14.8216 3.5827 16.7036 5.4647 16.7036 7.78627C16.7036 10.1078 14.8216 11.9898 12.5 11.9898C10.1784 11.9898 8.29645 10.1078 8.29645 7.78627Z"
                        fill="white"
                      />
                    </svg>
                    <p className="text-white text-[15px]">My Appointments</p>
                  </div>
                </Link>
              </Button>

              <Button
                variant={"ghost"}
                className="flex justify-start hover:bg-white/5 p-4 w-full"
              >
                <Link href="/doctor" passHref>
                  <div className="dashboardIcons">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="48"
                      height="48"
                      viewBox="0 0 25 25"
                      fill="none"
                    >
                      <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M12.5 2.08984C9.35397 2.08984 6.80359 4.64022 6.80359 7.78627C6.80359 10.3837 8.54197 12.575 10.9187 13.2604C9.04241 13.489 7.43306 14.1527 6.2207 15.3475C4.67769 16.8681 3.89648 19.132 3.89648 22.0862C3.89648 22.4984 4.23067 22.8326 4.64291 22.8326C5.05515 22.8326 5.38934 22.4984 5.38934 22.0862C5.38934 19.3833 6.10094 17.5615 7.26858 16.4107C8.43843 15.2578 10.1849 14.6613 12.4999 14.6613C14.815 14.6613 16.5615 15.2578 17.7314 16.4108C18.8991 17.5615 19.6107 19.3833 19.6107 22.0862C19.6107 22.4984 19.9448 22.8326 20.3571 22.8326C20.7693 22.8326 21.1035 22.4984 21.1035 22.0862C21.1036 19.132 20.3223 16.8681 18.7793 15.3475C17.5669 14.1527 15.9576 13.489 14.0813 13.2604C16.458 12.575 18.1964 10.3837 18.1964 7.78627C18.1964 4.64022 15.6461 2.08984 12.5 2.08984ZM8.29645 7.78627C8.29645 5.4647 10.1784 3.5827 12.5 3.5827C14.8216 3.5827 16.7036 5.4647 16.7036 7.78627C16.7036 10.1078 14.8216 11.9898 12.5 11.9898C10.1784 11.9898 8.29645 10.1078 8.29645 7.78627Z"
                        fill="white"
                      />
                    </svg>
                    <p className="text-white text-[15px]">Settings</p>
                  </div>
                </Link>
              </Button>

              
                
              
            </div>
          </div>

          <Button
            variant={"ghost"}
            className="flex justify-start hover:bg-white/5 pr-2 w-full"
          >
            <Link href="/" passHref>
              <div className="dashboardIcons">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 25 25"
                  fill="none"
                >
                  <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M7.78627 2.28711C7.35233 2.28711 7.00056 2.63889 7.00056 3.07282C7.00056 3.50676 7.35233 3.85854 7.78627 3.85854H19.572V21.1443H7.78627C7.35233 21.1443 7.00056 21.496 7.00056 21.93C7.00056 22.3639 7.35233 22.7157 7.78627 22.7157H19.572C20.4399 22.7157 21.1434 22.0121 21.1434 21.1443V3.85854C21.1434 2.99066 20.4399 2.28711 19.572 2.28711H7.78627ZM11.0919 8.4101C10.785 8.10326 10.2875 8.10326 9.98069 8.4101C9.67385 8.71694 9.67385 9.21442 9.98069 9.52127L12.1751 11.7157H1.50056C1.06662 11.7157 0.714844 12.0675 0.714844 12.5014C0.714844 12.9353 1.06662 13.2871 1.50056 13.2871H12.1751L9.98069 15.4815C9.67385 15.7884 9.67385 16.2859 9.98069 16.5927C10.2875 16.8995 10.785 16.8995 11.0919 16.5927L14.6276 13.057C14.9344 12.7501 14.9344 12.2527 14.6276 11.9458L11.0919 8.4101Z"
                    fill="white"
                  />
                </svg>
                <p className="text-[16px] text-white">Log out</p>
              </div>
            </Link>
          </Button>
        </div>

        <div className="flex flex-col bg-gray-50 h-[100%] items-center justify-start rounded-xl w-[100%]">
          <div className="nav-bar bg-white w-[100%] rounded-tl-lg flex item-center justify-between px-4 py-2">
            <div className="font-bold flex items-center text-secondary text-xl">
              {getActiveMenuName(pathname)}
            </div>
            <div className="flex gap-6 items-center">
              <div className=" flex gap-6">
                <ComboboxDemo />
                <Image src="/bell.svg" alt="bell" width={20} height={20} />
              </div>
              <div className="flex mr-2 gap-2">
                <Image src="/doctor.svg" alt="doctor" width={40} height={40} />
                <DropdownMenu>
                  <DropdownMenuTrigger>
                    {" "}
                    <Button
                      className=" p-1 px-2 flex gap-4 h-fit"
                      variant={"ghost"}
                    >
                      <div className="flex justify-start h-full flex-col">
                        <div className="text-sm  font-semibold">
                          Dr. John Doe
                        </div>
                        <div className="text-sm text-start font-normal">
                          Doctor
                        </div>
                      </div>
                      <Image
                        src="/chevron-down.svg"
                        alt="down-arrow"
                        width={16}
                        height={16}
                      />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent>
                    <DropdownMenuLabel>My Account</DropdownMenuLabel>
                    <DropdownMenuSeparator />
                    <DropdownMenuItem>Doctor</DropdownMenuItem>
                    <DropdownMenuItem>Admin</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
            </div>
          </div>
          <div className="h-[100%] w-full">{children}</div>
        </div>
      </div>
    </section>
  );
}
